# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
repository: austin-v-smith-econ/austin-v-smith-econ.github.io
title: Austin V. Smith
subtitle: Ph.D. Candidate in Economics <code>&#8212;</code> University of Arizona
email: austinvsmith@arizona.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! I am a Ph.D. Candidate in Economics at The University of Arizona. My research focuses on labor and public economics, with a particular interest in policing and crime.
# twitter_username: username
#github_username: austin-v-smith-econ
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _research
  - _cv

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
#  avatar : "/assets/images/bio-photo.jpg"
  bio    : " "
  links:
    - label: "austinvsmith@arizona.edu"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:austinvsmith@arizona.edu"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _research
  - scope:
      path: "_research"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "research"
  # _cv
  - scope:
      path: "_cv"
      type: pages
    values:
      layout: splash
